optimize: use bash, better errors

diff --git a/optimize b/optimize
--- a/optimize
+++ b/optimize
@@ -1,9 +1,12 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-set -u
+set -eu
+set -o pipefail
 
 syntax () {
 	cat <<- EOF
+${0} [arguments-to-optimize-world...]
+
 ${0} will do nearly all common administrative task needed under a Gentoo system.
 
 I will not sync the portage tree for you, because you may want to rerun multiple
@@ -13,32 +16,45 @@ times ${0} and do not want to flood the sync servers.
 	exit 1
 }
 
-if [ $# -gt 0 ] && [ \( "${1}" = '-h' -o "${1}" = '--help' \) ]
+if [ ${#} -gt 0 ] && [ \( "${1}" = '-h' -o "${1}" = '--help' \) ]
 then
 	syntax "${@}"
 fi
 
 tmpfile="$(mktemp)"
-status_file="$(mktemp)"
+running_cmd=''
 failed_cmd=''
 
 trap on_exit EXIT INT
 
 on_exit() {
-	status=$?
+	local status=${?}
+
+	if [ -n "${running_cmd}" ]
+	then
+		failed_cmd+="
+		${running_cmd}"
+		running_cmd=''
+	fi
 
 	if [ -n "${failed_cmd}" ]
 	then
-		echo 'some commands have failed'
+		# most case is ^C
+		[ ${status} -ne 0 ] && echo
+
+		echo '>> some commands have failed'
 		echo "${failed_cmd}" | tail -n +2 | while read l
 		do
-			echo " - ${l}"
+			echo ">>   - ${l}"
 		done
+
+		# reset for next run by exit
+		failed_cmd=''
 	fi
 
-	rm -f "${tmpfile}" "${status_file}"
+	rm -f "${tmpfile}"
 
-	exit $status
+	exit ${status}
 }
 
 unbuffer() {
@@ -64,27 +80,25 @@ run() {
 			opts='-- --color=y';;
 	esac
 
-	( unbuffer "${@}" ${opts} 2>&1; echo $? > "${status_file}" ) | tee "${tmpfile}"
-	status=$(cat "${status_file}")
-
-	if [ ${status} -ne 0 ]
+	set +e
+	running_cmd="${@}"
+	unbuffer "${@}" ${opts} 2>&1 | tee "${tmpfile}"
+	if [ ${?} -ne 0 ]
 	then
-		failed_cmd="${failed_cmd}
-		${@}"
+		failed_cmd+="
+		${running_cmd}"
+		running_cmd=''
 	fi
+	set -e
 
 	if [ -n "${regex}" ] && grep -q "${regex}" "${tmpfile}"
 	then
 		msg
 	fi
-
-	return ${status}
 }
 
 try_run() {
 	type "${1}" >/dev/null 2>&1 && run "${@}"
-
-	return $?
 }
 
 paludis_routine() {
@@ -92,7 +106,7 @@ paludis_routine() {
 	. /etc/paludis/bashrc
 	set -u
 
-	run	cave resolve --complete --continue-on-failure if-satisfied --execute world "$@"
+	run	cave resolve --complete --continue-on-failure if-satisfied --execute world "${@}"
 	run	cave fix-linkage
 	run	cave manage-search-index --create "${SEARCH_INDEX:-/var/paludis/index}"
 	run	cave purge --execute
@@ -100,7 +114,7 @@ paludis_routine() {
 }
 
 portage_routine() {
-	run	emerge --update --newuse --deep --with-bdeps=y --backtrack=999 @world "$@"
+	run	emerge --update --newuse --deep --with-bdeps=y --backtrack=999 @world "${@}"
 	try_run	smart-live-rebuild
 	run	emerge @preserved-rebuild
 	run	emerge --depclean
@@ -111,21 +125,19 @@ portage_routine() {
 	run	rm -rf /var/tmp/portage
 }
 
-# package manager
 case ${PACKAGE_MANAGER:-} in
 	paludis)
-		paludis_routine "$@"
+		paludis_routine "${@}"
 		;;
 	portage)
-		portage_routine "$@"
+		portage_routine "${@}"
 		;;
 	*)
-		echo 'no $PACKAGE_MANAGER set, defaulting to portage, make a PR for others.'
-		portage_routine "$@"
+		echo '>> no $PACKAGE_MANAGER set, defaulting to portage.'
+		portage_routine "${@}"
 		;;
 esac
 
-# system
 try_run	polipo -x
 try_run	updatedb
 try_run	rlpkg --all --reset
